**using adamax and LR = 0.002**

In [1]:
import numpy as np
import tensorflow as tf
import pickle
import numpy as np  # Add this line
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models

# Load data for non-defended dataset for OW training
def LoadDataWTFPAD_Training():

    print("Loading non-defended dataset for open-world scenario for training")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-defeneded-open-world-wtfpad/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    try:
        # Load training data
        with open(dataset_dir + 'X_train_WTFPAD.pkl', 'rb') as handle:
            X_train = np.array(pickle.load(handle, encoding='latin1'))
        print("X_train loaded")
        with open(dataset_dir + 'y_train_WTFPAD.pkl', 'rb') as handle:
            y_train = np.array(pickle.load(handle, encoding='latin1'))
        print("y_train loaded")

        # Load validation data
        with open(dataset_dir + 'X_valid_WTFPAD.pkl', 'rb') as handle:
            X_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("X_valid loaded")
        with open(dataset_dir + 'y_valid_WTFPAD.pkl', 'rb') as handle:
            y_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("y_valid loaded")

        print("Data dimensions:")
        print("X: Training data's shape : ", X_train.shape)
        print("y: Training data's shape : ", y_train.shape)
        print("X: Validation data's shape : ", X_valid.shape)
        print("y: Validation data's shape : ", y_valid.shape)
        
        print("Any None values in X_train:", np.any(np.isnan(X_train)))
        print("Any None values in y_train:", np.any(np.isnan(y_train)))
        print("Any None values in X_valid:", np.any(np.isnan(X_valid)))
        print("Any None values in y_valid:", np.any(np.isnan(y_valid)))
        
        # Merge datasets
        X_all = np.concatenate((X_train, X_valid), axis=0)
        y_all = np.concatenate((y_train, y_valid), axis=0)

        print("Merged data dimensions:")
        print("X: Merged data's shape : ", X_all.shape)
        print("y: Merged data's shape : ", y_all.shape)
        
        # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(X_all)
         # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(y_all)
        
       
        return X_all, y_all


    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load, merge, and balance data
X_all, y_all = LoadDataWTFPAD_Training()

2024-04-09 05:33:31.031586: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-09 05:33:31.031721: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-09 05:33:31.203587: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


Loading non-defended dataset for open-world scenario for training
X_train loaded
y_train loaded
X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (96000, 5000)
y: Training data's shape :  (96000,)
X: Validation data's shape :  (9600, 5000)
y: Validation data's shape :  (9600,)
Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False
Merged data dimensions:
X: Merged data's shape :  (105600, 5000)
y: Merged data's shape :  (105600,)
Features of the merged dataset:
[[-1. -1.  1. ...  1. -1.  1.]
 [-1.  1. -1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]
 ...
 [ 1. -1.  1. ...  0.  0.  0.]
 [ 1. -1.  1. ... -1. -1. -1.]
 [-1.  1.  1. ... -1.  1.  1.]]
Features of the merged dataset:
[80 83 95 ... 95 34 44]


In [3]:
import numpy as np
import tensorflow as tf
import pickle
import numpy as np  # Add this line
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout,ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models

# Load data for non-defended dataset for OW training
def LoadDataWTFPAD_Training():

    print("Loading non-defended dataset for open-world scenario for training")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-defeneded-open-world-wtfpad/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    try:
        # Load training data
        with open(dataset_dir + 'X_train_WTFPAD.pkl', 'rb') as handle:
            X_train = np.array(pickle.load(handle, encoding='latin1'))
        print("X_train loaded")
        with open(dataset_dir + 'y_train_WTFPAD.pkl', 'rb') as handle:
            y_train = np.array(pickle.load(handle, encoding='latin1'))
        print("y_train loaded")

        # Load validation data
        with open(dataset_dir + 'X_valid_WTFPAD.pkl', 'rb') as handle:
            X_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("X_valid loaded")
        with open(dataset_dir + 'y_valid_WTFPAD.pkl', 'rb') as handle:
            y_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("y_valid loaded")

        print("Data dimensions:")
        print("X: Training data's shape : ", X_train.shape)
        print("y: Training data's shape : ", y_train.shape)
        print("X: Validation data's shape : ", X_valid.shape)
        print("y: Validation data's shape : ", y_valid.shape)
        
        print("Any None values in X_train:", np.any(np.isnan(X_train)))
        print("Any None values in y_train:", np.any(np.isnan(y_train)))
        print("Any None values in X_valid:", np.any(np.isnan(X_valid)))
        print("Any None values in y_valid:", np.any(np.isnan(y_valid)))
        
        # Merge datasets
        X_all = np.concatenate((X_train, X_valid), axis=0)
        y_all = np.concatenate((y_train, y_valid), axis=0)

        print("Merged data dimensions:")
        print("X: Merged data's shape : ", X_all.shape)
        print("y: Merged data's shape : ", y_all.shape)
        
        # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(X_all)
         # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(y_all)
        
       
        return X_all, y_all


    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load, merge, and balance data
X_all, y_all =  LoadDataWTFPAD_Training() 


Loading non-defended dataset for open-world scenario for training
X_train loaded
y_train loaded
X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (96000, 5000)
y: Training data's shape :  (96000,)
X: Validation data's shape :  (9600, 5000)
y: Validation data's shape :  (9600,)
Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False
Merged data dimensions:
X: Merged data's shape :  (105600, 5000)
y: Merged data's shape :  (105600,)
Features of the merged dataset:
[[-1. -1.  1. ...  1. -1.  1.]
 [-1.  1. -1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]
 ...
 [ 1. -1.  1. ...  0.  0.  0.]
 [ 1. -1.  1. ... -1. -1. -1.]
 [-1.  1.  1. ... -1.  1.  1.]]
Features of the merged dataset:
[80 83 95 ... 95 34 44]


In [4]:
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adamax
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import save_model
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models
import numpy as np
from keras.layers import Activation

class DFNet:
    @staticmethod
    def build(input_shape, classes, dropout_rate1=0.3, dropout_rate2=0.5, dropout_rate_fc=0.7):
        model = Sequential()

        # ... (previous model definition remains unchanged)
        # Block 1
        filter_num = [None,32, 64, 128, 256]
        kernel_size = [None, 8, 8, 8, 8]
        conv_stride_size = [None, 1, 1, 1, 1]
        pool_stride_size = [None, 4, 4, 4, 4]
        pool_size = [None, 8, 8, 8, 8]

        for i in range(1, 4):
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             input_shape=input_shape if i == 1 else (None, input_shape[1]),
                             name=f'block{i}_conv1'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2 - 1}'))
            model.add(Activation('relu', name=f'block{i}_adv_act1'))
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             name=f'block{i}_conv2'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2}'))
            model.add(Activation('relu', name=f'block{i}_adv_act2'))

            model.add(MaxPooling1D(pool_size=pool_size[i], strides=pool_stride_size[i],
                                   padding='same', name=f'block{i}_pool'))
            model.add(Dropout(0.1, name=f'block{i}_dropout'))

        # ... (rest of the model remains unchanged)

        model.add(Flatten(name='flatten'))

        # Fully connected layers
        for i in range(1, 3):
            model.add(Dense(512, kernel_initializer=glorot_uniform(seed=0), name=f'fc{i}'))
            model.add(BatchNormalization(name=f'batch_normalization_{i + 8}'))
            model.add(Activation('relu', name=f'fc{i}_act'))

            # Experiment with different dropout rates
            model.add(Dropout(dropout_rate_fc, name=f'fc{i}_dropout'))

        # Output layer
        model.add(Dense(classes, kernel_initializer=glorot_uniform(seed=0), name='fc_final'))
        model.add(Activation('softmax', name="softmax"))

        print("Model built successfully.")
        return model
    # Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Build the model with the specified dropout rates
model = DFNet.build(input_shape=input_shape, classes=num_classes,
                    dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


# Print the model summary
print("Model Summary:")
model.summary()

# Compile the model
optimizer = Adamax(learning_rate=0.002)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])


# Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Load and merge data using the function you defined
X_all, y_all = LoadDataWTFPAD_Training()
# Define the number of folds
n_splits = 5  # You can adjust this as needed

# Initialize Stratified K-Fold
stratkf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Lists to store results
all_histories = []

# Iterate over folds
for fold, (train_index, test_index) in enumerate(stratkf.split(X_all, y_all)):
    print(f"\nTraining on Fold {fold + 1}/{n_splits}")

    # Split the data
    X_train, X_test = X_all[train_index], X_all[test_index]
    y_train, y_test = y_all[train_index], y_all[test_index]
    
        # Build the model
    model = DFNet.build(input_shape=input_shape, classes=num_classes,
                        dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)

    # Compile the model
    optimizer = Adamax(learning_rate=0.002)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
     # Define early stopping callback
    early_stopping = EarlyStopping(monitor='val_loss', patience=25, restore_best_weights=True)

    # Train the model with early stopping
    history = model.fit(X_train, y_train, epochs= 25, batch_size=64, 
                        validation_data=(X_test, y_test), verbose=2, callbacks=[early_stopping])
    
    # Train the model
    #history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test), verbose=2)

    # Evaluate the model on the test set
    loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
    print(f"\nFold {fold + 1} - Test Accuracy: {accuracy * 100:.2f}%")

    # Save history for later analysis if needed
    all_histories.append(history)
    # Check unique labels in y_train
    
    # Update num_classes based on the actual number of unique classes in your dataset
#num_classes = len(np.unique(y_all))
model_save_path = '/kaggle/working/DFNet_OpenWorld_WTFPAD.keras'
save_model(model,model_save_path)

print("Trained model saved successfully at:", model_save_path)


/opt/conda/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Model built successfully.
Model Summary:


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ block1_conv1 (Conv1D)           │ (None, 5000, 32)       │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 5000, 32)       │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_adv_act1 (Activation)    │ (None, 5000, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_conv2 (Conv1D)           │ (None, 5000, 32)       │         8,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 5000, 32)       │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_adv_act2 (Activation)    │ (None, 5000, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_pool (MaxPooling1D)      │ (None, 1250, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_dropout (Dropout)        │ (None, 1250, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv1 (Conv1D)           │ (None, 1250, 64)       │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 1250, 64)       │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_adv_act1 (Activation)    │ (None, 1250, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv2 (Conv1D)           │ (None, 1250, 64)       │        32,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 1250, 64)       │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_adv_act2 (Activation)    │ (None, 1250, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_pool (MaxPooling1D)      │ (None, 313, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_dropout (Dropout)        │ (None, 313, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv1 (Conv1D)           │ (None, 313, 128)       │        65,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 313, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_adv_act1 (Activation)    │ (None, 313, 128)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv2 (Conv1D)           │ (None, 313, 128)       │       131,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 313, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_adv_act2 (Activation)    │ (None, 313, 128)       │             

 Total params: 5,750,304 (21.94 MB)

 Trainable params: 5,747,360 (21.92 MB)

 Non-trainable params: 2,944 (11.50 KB)

Loading non-defended dataset for open-world scenario for training
X_train loaded
y_train loaded
X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (96000, 5000)
y: Training data's shape :  (96000,)
X: Validation data's shape :  (9600, 5000)
y: Validation data's shape :  (9600,)
Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False
Merged data dimensions:
X: Merged data's shape :  (105600, 5000)
y: Merged data's shape :  (105600,)
Features of the merged dataset:
[[-1. -1.  1. ...  1. -1.  1.]
 [-1.  1. -1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]
 ...
 [ 1. -1.  1. ...  0.  0.  0.]
 [ 1. -1.  1. ... -1. -1. -1.]
 [-1.  1.  1. ... -1.  1.  1.]]
Features of the merged dataset:
[80 83 95 ... 95 34 44]

Training on Fold 1/5


/opt/conda/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Model built successfully.
Epoch 1/25


I0000 00:00:1712641021.964071     116 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
W0000 00:00:1712641021.996314     116 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1712641121.422323     115 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1320/1320 - 127s - 96ms/step - accuracy: 0.3458 - loss: 2.4371 - val_accuracy: 0.3451 - val_loss: 2.5501
Epoch 2/25
1320/1320 - 102s - 77ms/step - accuracy: 0.5458 - loss: 1.5788 - val_accuracy: 0.5869 - val_loss: 1.5139
Epoch 3/25
1320/1320 - 101s - 77ms/step - accuracy: 0.6344 - loss: 1.2625 - val_accuracy: 0.7098 - val_loss: 1.0192
Epoch 4/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6875 - loss: 1.0701 - val_accuracy: 0.7458 - val_loss: 0.8728
Epoch 5/25
1320/1320 - 101s - 77ms/step - accuracy: 0.7277 - loss: 0.9344 - val_accuracy: 0.7336 - val_loss: 0.9059
Epoch 6/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7529 - loss: 0.8384 - val_accuracy: 0.7778 - val_loss: 0.7765
Epoch 7/25
1320/1320 - 101s - 77ms/step - accuracy: 0.7732 - loss: 0.7666 - val_accuracy: 0.8039 - val_loss: 0.6794
Epoch 8/25
1320/1320 - 101s - 77ms/step - accuracy: 0.7922 - loss: 0.7004 - val_accuracy: 0.7991 - val_loss: 0.6921
Epoch 9/25
1320/1320 - 142s - 108ms/step - accuracy: 0.8061 - loss: 0.6471 - val_ac

W0000 00:00:1712643642.111419     116 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


660/660 - 5s - 8ms/step - accuracy: 0.8223 - loss: 0.6278

Fold 1 - Test Accuracy: 82.23%

Training on Fold 2/5
Model built successfully.
Epoch 1/25


W0000 00:00:1712643664.703838     113 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1712643765.081825     114 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1320/1320 - 117s - 88ms/step - accuracy: 0.3531 - loss: 2.4104 - val_accuracy: 0.5274 - val_loss: 1.6742
Epoch 2/25
1320/1320 - 102s - 77ms/step - accuracy: 0.5637 - loss: 1.5220 - val_accuracy: 0.6607 - val_loss: 1.1823
Epoch 3/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6465 - loss: 1.2201 - val_accuracy: 0.7272 - val_loss: 0.9587
Epoch 4/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6967 - loss: 1.0403 - val_accuracy: 0.7336 - val_loss: 0.9239
Epoch 5/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7302 - loss: 0.9186 - val_accuracy: 0.7750 - val_loss: 0.7955
Epoch 6/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7566 - loss: 0.8223 - val_accuracy: 0.7864 - val_loss: 0.7412
Epoch 7/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7759 - loss: 0.7507 - val_accuracy: 0.7943 - val_loss: 0.7092
Epoch 8/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7941 - loss: 0.6862 - val_accuracy: 0.8009 - val_loss: 0.6966
Epoch 9/25
1320/1320 - 102s - 77ms/step - accuracy: 0.8097 - loss: 0.6341 - val_acc

W0000 00:00:1712646220.896559     114 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


660/660 - 4s - 6ms/step - accuracy: 0.8249 - loss: 0.6307

Fold 2 - Test Accuracy: 82.49%

Training on Fold 3/5
Model built successfully.
Epoch 1/25


W0000 00:00:1712646243.280812     115 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1712646343.825091     116 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1320/1320 - 116s - 88ms/step - accuracy: 0.3376 - loss: 2.4775 - val_accuracy: 0.4748 - val_loss: 1.8673
Epoch 2/25
1320/1320 - 102s - 77ms/step - accuracy: 0.5505 - loss: 1.5705 - val_accuracy: 0.6473 - val_loss: 1.2186
Epoch 3/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6396 - loss: 1.2440 - val_accuracy: 0.7020 - val_loss: 1.0197
Epoch 4/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6924 - loss: 1.0578 - val_accuracy: 0.7426 - val_loss: 0.8818
Epoch 5/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7255 - loss: 0.9378 - val_accuracy: 0.7683 - val_loss: 0.7925
Epoch 6/25
1320/1320 - 101s - 77ms/step - accuracy: 0.7533 - loss: 0.8394 - val_accuracy: 0.7496 - val_loss: 0.8428
Epoch 7/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7734 - loss: 0.7662 - val_accuracy: 0.7886 - val_loss: 0.7255
Epoch 8/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7894 - loss: 0.7037 - val_accuracy: 0.8071 - val_loss: 0.6717
Epoch 9/25
1320/1320 - 101s - 77ms/step - accuracy: 0.8031 - loss: 0.6532 - val_acc

W0000 00:00:1712648783.458647     116 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


660/660 - 4s - 6ms/step - accuracy: 0.8327 - loss: 0.6234

Fold 3 - Test Accuracy: 83.27%

Training on Fold 4/5
Model built successfully.
Epoch 1/25


W0000 00:00:1712648806.480645     114 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1712648907.256637     113 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1320/1320 - 117s - 88ms/step - accuracy: 0.3449 - loss: 2.4461 - val_accuracy: 0.4753 - val_loss: 1.8730
Epoch 2/25
1320/1320 - 102s - 78ms/step - accuracy: 0.5540 - loss: 1.5552 - val_accuracy: 0.5607 - val_loss: 1.5218
Epoch 3/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6423 - loss: 1.2349 - val_accuracy: 0.6947 - val_loss: 1.0563
Epoch 4/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6942 - loss: 1.0502 - val_accuracy: 0.7383 - val_loss: 0.9011
Epoch 5/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7280 - loss: 0.9306 - val_accuracy: 0.7206 - val_loss: 0.9683
Epoch 6/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7542 - loss: 0.8353 - val_accuracy: 0.7722 - val_loss: 0.7875
Epoch 7/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7760 - loss: 0.7614 - val_accuracy: 0.7932 - val_loss: 0.7095
Epoch 8/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7931 - loss: 0.6986 - val_accuracy: 0.7895 - val_loss: 0.7225
Epoch 9/25
1320/1320 - 102s - 77ms/step - accuracy: 0.8056 - loss: 0.6489 - val_acc

W0000 00:00:1712651397.795052     113 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


660/660 - 4s - 6ms/step - accuracy: 0.8103 - loss: 0.6638

Fold 4 - Test Accuracy: 81.03%

Training on Fold 5/5
Model built successfully.
Epoch 1/25


W0000 00:00:1712651420.501038     114 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1712651521.072781     115 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1320/1320 - 117s - 88ms/step - accuracy: 0.3595 - loss: 2.3808 - val_accuracy: 0.5408 - val_loss: 1.6299
Epoch 2/25
1320/1320 - 102s - 77ms/step - accuracy: 0.5666 - loss: 1.5171 - val_accuracy: 0.6050 - val_loss: 1.3568
Epoch 3/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6469 - loss: 1.2167 - val_accuracy: 0.7221 - val_loss: 0.9654
Epoch 4/25
1320/1320 - 102s - 77ms/step - accuracy: 0.6935 - loss: 1.0441 - val_accuracy: 0.7372 - val_loss: 0.9236
Epoch 5/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7285 - loss: 0.9195 - val_accuracy: 0.7596 - val_loss: 0.8154
Epoch 6/25
1320/1320 - 142s - 108ms/step - accuracy: 0.7550 - loss: 0.8312 - val_accuracy: 0.7789 - val_loss: 0.7647
Epoch 7/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7755 - loss: 0.7528 - val_accuracy: 0.7896 - val_loss: 0.7401
Epoch 8/25
1320/1320 - 102s - 77ms/step - accuracy: 0.7928 - loss: 0.6920 - val_accuracy: 0.7984 - val_loss: 0.6938
Epoch 9/25
1320/1320 - 102s - 77ms/step - accuracy: 0.8094 - loss: 0.6355 - val_ac

W0000 00:00:1712654005.822986     113 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


660/660 - 4s - 6ms/step - accuracy: 0.8286 - loss: 0.6273

Fold 5 - Test Accuracy: 82.86%
Trained model saved successfully at: /kaggle/working/DFNet_OpenWorld_WTFPAD.keras


In [33]:
# Save the model to the Kaggle output directory
model_save_path = '/kaggle/working/DFNet_OpenWorld_WTFPAD.keras'
model.save(model_save_path)
print("Trained model saved successfully at:", model_save_path)


Trained model saved successfully at: /kaggle/working/DFNet_OpenWorld_WTFPAD.keras


In [37]:
import os

# Define the directory for saving the model
expected_directory = '/kaggle/working/'
expected_filename = 'DFNet_OpenWorld_WTFPAD.keras'

# Construct the full path
saved_path_keras = os.path.join(expected_directory, expected_filename)

# Check if the directory exists
if not os.path.exists(expected_directory):
    print("Error: Directory does not exist:", expected_directory)
else:
    # Check if the model was saved successfully
    try:
        # Your code for saving the model goes here
        # For example:
        # model.save(saved_path_keras)
        # If an error occurs during the saving process, it will be caught here
        print("Model saved successfully.")
    except Exception as e:
        print("Error occurred while saving the model:", e)


Model saved successfully.


**evaluation**

In [40]:
# Load data for non-defended dataset for OW evaluation
import pickle
import numpy as np
def LoadDataWTFPADOW_Evaluation():

    print("Loading defended dataset for open-world scenario for evaluation")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-defeneded-open-world-wtfpad/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)
    try:
        # Load testing data
        with open(dataset_dir + 'X_test_Mon_WTFPAD.pkl', 'rb') as handle:
            X_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Mon_WTFPAD.pkl', 'rb') as handle:
            y_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'X_test_Unmon_WTFPAD.pkl', 'rb') as handle:
            X_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Unmon_WTFPAD.pkl', 'rb') as handle:
            y_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))

        X_test_Mon = np.array(X_test_Mon)
        y_test_Mon = np.array(y_test_Mon)
        X_test_Unmon = np.array(X_test_Unmon)
        y_test_Unmon = np.array(y_test_Unmon)

        return X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon

    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load evaluation data
LoadDataWTFPADOW_Evaluation()

Loading defended dataset for open-world scenario for evaluation


(array([[ 1.,  1., -1., ...,  0.,  0.,  0.],
        [ 1., -1.,  1., ...,  0.,  0.,  0.],
        [ 1.,  1.,  1., ...,  0.,  0.,  0.],
        ...,
        [-1.,  1., -1., ...,  0.,  0.,  0.],
        [-1.,  1., -1., ...,  0.,  0.,  0.],
        [ 1.,  1., -1., ...,  0.,  0.,  0.]]),
 array([ 0,  0,  0, ..., 94, 94, 94]),
 array([[ 1., -1.,  1., ...,  0.,  0.,  0.],
        [ 1., -1.,  1., ..., -1., -1., -1.],
        [-1.,  1., -1., ...,  0.,  0.,  0.],
        ...,
        [-1., -1., -1., ..., -1., -1.,  1.],
        [-1.,  1., -1., ...,  0.,  0.,  0.],
        [-1.,  1., -1., ...,  0.,  0.,  0.]]),
 array([95, 95, 95, ..., 95, 95, 95]))

In [41]:
from keras.models import load_model
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

def Prediction(trained_model = None, dataset = None):
    X_test_Mon = dataset['X_test_Mon'].astype('float32')
    X_test_Unmon = dataset['X_test_Unmon'].astype('float32')
    print ("Total testing data ", len(X_test_Mon) + len(X_test_Unmon))
    X_test_Mon = X_test_Mon[:, :, np.newaxis]
    X_test_Unmon = X_test_Unmon[:, :, np.newaxis]
    result_Mon = trained_model.predict(X_test_Mon, verbose=2)
    result_Unmon = trained_model.predict(X_test_Unmon, verbose=2)
    return result_Mon, result_Unmon
def Evaluation(threshold_val = None, monitored_label = None,
                   unmonitored_label = None, result_Mon = None,
                   result_Unmon = None, log_file = None):
    print ("Testing with threshold = ", threshold_val)
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    # ==============================================================
    # Test with Monitored testing instances
    # evaluation
    for i in range(len(result_Mon)):
        sm_vector = result_Mon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Monitored
                TP = TP + 1
            else: # predicted as Unmonitored and actual site is Monitored
                FN = FN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Monitored
            FN = FN + 1

    # ==============================================================
    # Test with Unmonitored testing instances
    # evaluation
    for i in range(len(result_Unmon)):
        sm_vector = result_Unmon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Unmonitored
                FP = FP + 1
            else: # predicted as Unmonitored and actual site is Unmonitored
                TN = TN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Unmonitored
            TN = TN + 1
            
    print ("TP : ", TP)
    print ("FP : ", FP)
    print ("TN : ", TN)
    print ("FN : ", FN)
    print ("Total  : ", TP + FP + TN + FN)
    TPR = float(TP) / (TP + FN)
    print ("TPR : ", TPR)
    FPR = float(FP) / (FP + TN)
    print ("FPR : ",  FPR)
    Precision = float(TP) / (TP + FP)
    print ("Precision : ", Precision)
    Recall = float(TP) / (TP + FN)
    print ("Recall : ", Recall)
    print ("\n")
    log_file.writelines("%.6f,%d,%d,%d,%d,%.6f,%.6f,%.6f,%.6f\n"%(threshold_val, TP, FP, TN, FN, TPR, FPR, Precision, Recall))

# The evaluation of Open World scenario
def OW_Evaluation():
    evaluation_type = 'OpenWorld_WTFPAD'
    print("Evaluation type: ", evaluation_type)

    # Create the 'results' directory if it doesn't exist
    results_dir = '../results/'
    os.makedirs(results_dir, exist_ok=True)

    threshold = 1.0 - 1 / np.logspace(0.05, 2, num=15, endpoint=True)
    file_name = f'{results_dir}{evaluation_type}.csv'
    log_file = open(file_name, "w")  # Open the file in text mode, not binary mode
    # Load data
    dataset = {}
    model_name = ''
    print ("Loading data ...")
    #from utility import LoadDataNoDefOW_Evaluation
    X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon = LoadDataWTFPADOW_Evaluation()
    # Load pre-trained model saved from 'Open_World_DF_***_Training.py'
    #model_name = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
    model_name = '/kaggle/working/DFNet_OpenWorld_WTFPAD.keras'


    dataset['X_test_Mon'] = X_test_Mon
    dataset['y_test_Mon'] = y_test_Mon
    dataset['X_test_Unmon'] = X_test_Unmon
    dataset['y_test_Unmon'] = y_test_Unmon

    print ("Data loaded!")
    print ("Loading DF model ...")
    print ("The log file will be saved at ", file_name)
    print ("-- The log file will contains")
    print ("-- TP, FP, TN, FN, TPR, FPR, Precision, and Recall for each different threshold")
    print ("-- These results will be used to plot the ROC or Precision&Recall Graph")
    trained_model = load_model(model_name)
    print ("Model loaded!")
    print ("Evaluation Type: ", evaluation_type)
    print ("Use the model from ", model_name)
    result_Mon, result_Unmon = Prediction(trained_model = trained_model, dataset = dataset)
    monitored_label = list(y_test_Mon)
    unmonitored_label = list(y_test_Unmon)
    log_file.writelines("%s,%s,%s,%s,%s,%s  ,%s  ,  %s, %s\n" % ('Threshold', 'TP', 'FP', 'TN', 'FN', 'TPR', 'FPR', 'Precision', 'Recall'))
    for th in threshold:
        Evaluation(threshold_val = th, monitored_label = monitored_label,
                   unmonitored_label = unmonitored_label, result_Mon = result_Mon,
                   result_Unmon = result_Unmon, log_file = log_file)
    log_file.close()  

OW_Evaluation()

Evaluation type:  OpenWorld_WTFPAD
Loading data ...
Loading defended dataset for open-world scenario for evaluation
Data loaded!
Loading DF model ...
The log file will be saved at  ../results/OpenWorld_WTFPAD.csv
-- The log file will contains
-- TP, FP, TN, FN, TPR, FPR, Precision, and Recall for each different threshold
-- These results will be used to plot the ROC or Precision&Recall Graph
Model loaded!
Evaluation Type:  OpenWorld_WTFPAD
Use the model from  /kaggle/working/DFNet_OpenWorld_WTFPAD.keras
Total testing data  29500


W0000 00:00:1712684277.150353     110 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


297/297 - 2s - 8ms/step


W0000 00:00:1712684278.954388     107 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


625/625 - 2s - 4ms/step
Testing with threshold =  0.10874906186625455
TP :  8689
FP :  10259
TN :  9741
FN :  811
Total  :  29500
TPR :  0.9146315789473685
FPR :  0.51295
Precision :  0.45857082541693056
Recall :  0.9146315789473685


Testing with threshold =  0.35328298736360164
TP :  7185
FP :  6799
TN :  13201
FN :  2315
Total  :  29500
TPR :  0.7563157894736842
FPR :  0.33995
Precision :  0.5138014874141876
Recall :  0.7563157894736842


Testing with threshold =  0.5307237540651162
TP :  5493
FP :  3369
TN :  16631
FN :  4007
Total  :  29500
TPR :  0.5782105263157895
FPR :  0.16845
Precision :  0.6198375084631009
Recall :  0.5782105263157895


Testing with threshold =  0.6594798177629646
TP :  4442
FP :  1780
TN :  18220
FN :  5058
Total  :  29500
TPR :  0.46757894736842104
FPR :  0.089
Precision :  0.7139183542269367
Recall :  0.46757894736842104


Testing with threshold =  0.7529088772014396
TP :  3691
FP :  1048
TN :  18952
FN :  5809
Total  :  29500
TPR :  0.38852631578947366
F

**FOR defended WalkieTalkie open world**

In [10]:
import numpy as np
import tensorflow as tf
import pickle
import numpy as np  # Add this line
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models

# Load data for non-defended dataset for OW training
def LoadDataWalkieTalkie_Training():

    print("Loading non-defended dataset for open-world scenario for training")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/defended-open-world-walkietalkie-dataset/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    try:
        # Load training data
        with open(dataset_dir + 'X_train_WalkieTalkie.pkl', 'rb') as handle:
            X_train = np.array(pickle.load(handle, encoding='latin1'))
        print("X_train loaded")
        with open(dataset_dir + 'y_train_WalkieTalkie.pkl', 'rb') as handle:
            y_train = np.array(pickle.load(handle, encoding='latin1'))
        print("y_train loaded")

        # Load validation data
        with open(dataset_dir + 'X_valid_WalkieTalkie.pkl', 'rb') as handle:
            X_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("X_valid loaded")
        with open(dataset_dir + 'y_valid_WalkieTalkie.pkl', 'rb') as handle:
            y_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("y_valid loaded")

        print("Data dimensions:")
        print("X: Training data's shape : ", X_train.shape)
        print("y: Training data's shape : ", y_train.shape)
        print("X: Validation data's shape : ", X_valid.shape)
        print("y: Validation data's shape : ", y_valid.shape)
        
        print("Any None values in X_train:", np.any(np.isnan(X_train)))
        print("Any None values in y_train:", np.any(np.isnan(y_train)))
        print("Any None values in X_valid:", np.any(np.isnan(X_valid)))
        print("Any None values in y_valid:", np.any(np.isnan(y_valid)))
        
        # Merge datasets
        X_all = np.concatenate((X_train, X_valid), axis=0)
        y_all = np.concatenate((y_train, y_valid), axis=0)

        print("Merged data dimensions:")
        print("X: Merged data's shape : ", X_all.shape)
        print("y: Merged data's shape : ", y_all.shape)
        
        # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(X_all)
         # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(y_all)
        
       
        return X_all, y_all


    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load, merge, and balance data
X_all, y_all = LoadDataWalkieTalkie_Training()

Loading non-defended dataset for open-world scenario for training
X_train loaded
y_train loaded
X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (99000, 5000)
y: Training data's shape :  (99000,)
X: Validation data's shape :  (2000, 5000)
y: Validation data's shape :  (2000,)
Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False
Merged data dimensions:
X: Merged data's shape :  (101000, 5000)
y: Merged data's shape :  (101000,)
Features of the merged dataset:
[[ 1  1 -1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1 -1 -1]
 [ 1 -1  1 ... -1 -1 -1]
 ...
 [ 1 -1  1 ...  0  0  0]
 [ 1  1  1 ... -1 -1 -1]
 [ 1 -1  1 ... -1 -1 -1]]
Features of the merged dataset:
[ 82  88  32 ... 100  40  53]


In [13]:
import numpy as np
import tensorflow as tf
import pickle
import numpy as np  # Add this line
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout,ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models

# Load data for non-defended dataset for OW training
def LoadDataWalkieTalkie_Training():

    print("Loading defended dataset for open-world scenario for training")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/defended-open-world-walkietalkie-dataset/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    try:
        # Load training data
        with open(dataset_dir + 'X_train_WalkieTalkie.pkl', 'rb') as handle:
            X_train = np.array(pickle.load(handle, encoding='latin1'))
        print("X_train loaded")
        with open(dataset_dir + 'y_train_WalkieTalkie.pkl', 'rb') as handle:
            y_train = np.array(pickle.load(handle, encoding='latin1'))
        print("y_train loaded")

        # Load validation data
        with open(dataset_dir + 'X_valid_WalkieTalkie.pkl', 'rb') as handle:
            X_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("X_valid loaded")
        with open(dataset_dir + 'y_valid_WalkieTalkie.pkl', 'rb') as handle:
            y_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("y_valid loaded")

        print("Data dimensions:")
        print("X: Training data's shape : ", X_train.shape)
        print("y: Training data's shape : ", y_train.shape)
        print("X: Validation data's shape : ", X_valid.shape)
        print("y: Validation data's shape : ", y_valid.shape)
        
        print("Any None values in X_train:", np.any(np.isnan(X_train)))
        print("Any None values in y_train:", np.any(np.isnan(y_train)))
        print("Any None values in X_valid:", np.any(np.isnan(X_valid)))
        print("Any None values in y_valid:", np.any(np.isnan(y_valid)))
        
        # Merge datasets
        X_all = np.concatenate((X_train, X_valid), axis=0)
        y_all = np.concatenate((y_train, y_valid), axis=0)

        print("Merged data dimensions:")
        print("X: Merged data's shape : ", X_all.shape)
        print("y: Merged data's shape : ", y_all.shape)
        
        # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(X_all)
         # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(y_all)
        
       
        return X_all, y_all


    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load, merge, and balance data
X_all, y_all = LoadDataWalkieTalkie_Training()


Loading defended dataset for open-world scenario for training
X_train loaded
y_train loaded
X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (99000, 5000)
y: Training data's shape :  (99000,)
X: Validation data's shape :  (2000, 5000)
y: Validation data's shape :  (2000,)
Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False
Merged data dimensions:
X: Merged data's shape :  (101000, 5000)
y: Merged data's shape :  (101000,)
Features of the merged dataset:
[[ 1  1 -1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1 -1 -1]
 [ 1 -1  1 ... -1 -1 -1]
 ...
 [ 1 -1  1 ...  0  0  0]
 [ 1  1  1 ... -1 -1 -1]
 [ 1 -1  1 ... -1 -1 -1]]
Features of the merged dataset:
[ 82  88  32 ... 100  40  53]


In [14]:
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adamax
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import save_model
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models
import numpy as np
from keras.layers import Activation

class DFNet:
    @staticmethod
    def build(input_shape, classes, dropout_rate1=0.3, dropout_rate2=0.5, dropout_rate_fc=0.7):
        model = Sequential()

        # ... (previous model definition remains unchanged)
        # Block 1
        filter_num = [None,32, 64, 128, 256]
        kernel_size = [None, 8, 8, 8, 8]
        conv_stride_size = [None, 1, 1, 1, 1]
        pool_stride_size = [None, 4, 4, 4, 4]
        pool_size = [None, 8, 8, 8, 8]

        for i in range(1, 4):
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             input_shape=input_shape if i == 1 else (None, input_shape[1]),
                             name=f'block{i}_conv1'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2 - 1}'))
            model.add(Activation('relu', name=f'block{i}_adv_act1'))
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             name=f'block{i}_conv2'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2}'))
            model.add(Activation('relu', name=f'block{i}_adv_act2'))

            model.add(MaxPooling1D(pool_size=pool_size[i], strides=pool_stride_size[i],
                                   padding='same', name=f'block{i}_pool'))
            model.add(Dropout(0.1, name=f'block{i}_dropout'))

        # ... (rest of the model remains unchanged)

        model.add(Flatten(name='flatten'))

        # Fully connected layers
        for i in range(1, 3):
            model.add(Dense(512, kernel_initializer=glorot_uniform(seed=0), name=f'fc{i}'))
            model.add(BatchNormalization(name=f'batch_normalization_{i + 8}'))
            model.add(Activation('relu', name=f'fc{i}_act'))

            # Experiment with different dropout rates
            model.add(Dropout(dropout_rate_fc, name=f'fc{i}_dropout'))

        # Output layer
        model.add(Dense(classes, kernel_initializer=glorot_uniform(seed=0), name='fc_final'))
        model.add(Activation('softmax', name="softmax"))

        print("Model built successfully.")
        return model
    # Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Build the model with the specified dropout rates
model = DFNet.build(input_shape=input_shape, classes=num_classes,
                    dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


# Print the model summary
print("Model Summary:")
model.summary()

# Compile the model
optimizer = Adamax(learning_rate=0.002)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])


# Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Load and merge data using the function you defined
X_all, y_all = LoadDataWalkieTalkie_Training()
# Define the number of folds
n_splits = 5  # You can adjust this as needed

# Initialize Stratified K-Fold
stratkf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Lists to store results
all_histories = []

# Iterate over folds
for fold, (train_index, test_index) in enumerate(stratkf.split(X_all, y_all)):
    print(f"\nTraining on Fold {fold + 1}/{n_splits}")

    # Split the data
    X_train, X_test = X_all[train_index], X_all[test_index]
    y_train, y_test = y_all[train_index], y_all[test_index]
    
        # Build the model
    model = DFNet.build(input_shape=input_shape, classes=num_classes,
                        dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)

    # Compile the model
    optimizer = Adamax(learning_rate=0.002)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
     # Define early stopping callback
    early_stopping = EarlyStopping(monitor='val_loss', patience=25, restore_best_weights=True)

    # Train the model with early stopping
    history = model.fit(X_train, y_train, epochs= 25, batch_size=64, 
                        validation_data=(X_test, y_test), verbose=2, callbacks=[early_stopping])
    
    # Train the model
    #history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test), verbose=2)

    # Evaluate the model on the test set
    loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
    print(f"\nFold {fold + 1} - Test Accuracy: {accuracy * 100:.2f}%")

    # Save history for later analysis if needed
    all_histories.append(history)
    # Check unique labels in y_train
    
    # Update num_classes based on the actual number of unique classes in your dataset
#num_classes = len(np.unique(y_all))
model_save_path = '/kaggle/working/DFNet_OpenWorld_WALKIETALKIE.keras'
save_model(model,model_save_path)

print("Trained model saved successfully at:", model_save_path)


/opt/conda/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Model built successfully.
Model Summary:


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ block1_conv1 (Conv1D)           │ (None, 5000, 32)       │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 5000, 32)       │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_adv_act1 (Activation)    │ (None, 5000, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_conv2 (Conv1D)           │ (None, 5000, 32)       │         8,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 5000, 32)       │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_adv_act2 (Activation)    │ (None, 5000, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_pool (MaxPooling1D)      │ (None, 1250, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_dropout (Dropout)        │ (None, 1250, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv1 (Conv1D)           │ (None, 1250, 64)       │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 1250, 64)       │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_adv_act1 (Activation)    │ (None, 1250, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv2 (Conv1D)           │ (None, 1250, 64)       │        32,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 1250, 64)       │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_adv_act2 (Activation)    │ (None, 1250, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_pool (MaxPooling1D)      │ (None, 313, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_dropout (Dropout)        │ (None, 313, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv1 (Conv1D)           │ (None, 313, 128)       │        65,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 313, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_adv_act1 (Activation)    │ (None, 313, 128)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv2 (Conv1D)           │ (None, 313, 128)       │       131,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 313, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_adv_act2 (Activation)    │ (None, 313, 128)       │             

 Total params: 5,750,304 (21.94 MB)

 Trainable params: 5,747,360 (21.92 MB)

 Non-trainable params: 2,944 (11.50 KB)

Loading defended dataset for open-world scenario for training
X_train loaded
y_train loaded
X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (99000, 5000)
y: Training data's shape :  (99000,)
X: Validation data's shape :  (2000, 5000)
y: Validation data's shape :  (2000,)
Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False
Merged data dimensions:
X: Merged data's shape :  (101000, 5000)
y: Merged data's shape :  (101000,)
Features of the merged dataset:
[[ 1  1 -1 ... -1 -1 -1]
 [ 1 -1 -1 ... -1 -1 -1]
 [ 1 -1  1 ... -1 -1 -1]
 ...
 [ 1 -1  1 ...  0  0  0]
 [ 1  1  1 ... -1 -1 -1]
 [ 1 -1  1 ... -1 -1 -1]]
Features of the merged dataset:
[ 82  88  32 ... 100  40  53]

Training on Fold 1/5


/opt/conda/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Model built successfully.
Epoch 1/25


I0000 00:00:1713168485.589422     199 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
W0000 00:00:1713168485.615563     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713168592.549493     202 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713168595.443508     201 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 139s - 110ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 2/25


W0000 00:00:1713168599.716981     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 3/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 4/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 5/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 6/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 7/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 8/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 9/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 10/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 11/25
1263/1263 - 95s -

W0000 00:00:1713170933.756620     200 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


632/632 - 5s - 7ms/step - accuracy: 0.0080 - loss: nan


W0000 00:00:1713170937.782893     201 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update



Fold 1 - Test Accuracy: 0.80%

Training on Fold 2/5
Model built successfully.
Epoch 1/25


W0000 00:00:1713170960.385220     202 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713171062.347481     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713171065.039131     200 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 121s - 96ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 2/25


W0000 00:00:1713171067.944646     201 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 3/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 4/25
1263/1263 - 142s - 112ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 5/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 6/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 7/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 8/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 9/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 10/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 11/25
1263/1263 - 95s

W0000 00:00:1713173446.952130     200 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


632/632 - 4s - 6ms/step - accuracy: 0.0080 - loss: nan


W0000 00:00:1713173450.207578     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update



Fold 2 - Test Accuracy: 0.80%

Training on Fold 3/5
Model built successfully.
Epoch 1/25


W0000 00:00:1713173473.246275     202 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713173575.804054     202 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713173578.528359     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 122s - 97ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 2/25


W0000 00:00:1713173581.440620     200 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 3/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 4/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 5/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 6/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 7/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 8/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 9/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 10/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 11/25
1263/1263 - 95s -

W0000 00:00:1713175868.530578     202 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


632/632 - 4s - 6ms/step - accuracy: 0.0080 - loss: nan


W0000 00:00:1713175871.734266     200 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update



Fold 3 - Test Accuracy: 0.80%

Training on Fold 4/5
Model built successfully.
Epoch 1/25


W0000 00:00:1713175894.676360     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713175997.116211     202 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713175999.805790     200 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 122s - 97ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 2/25


W0000 00:00:1713176002.765986     202 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 3/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 4/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 5/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 6/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 7/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 8/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 9/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 10/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 11/25
1263/1263 - 95s -

W0000 00:00:1713178288.773698     201 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


632/632 - 4s - 6ms/step - accuracy: 0.0080 - loss: nan


W0000 00:00:1713178291.977251     200 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update



Fold 4 - Test Accuracy: 0.80%

Training on Fold 5/5
Model built successfully.
Epoch 1/25


W0000 00:00:1713178315.608024     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713178417.305489     201 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
W0000 00:00:1713178420.004652     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 122s - 97ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 2/25


W0000 00:00:1713178422.997283     201 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 3/25
1263/1263 - 95s - 76ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 4/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 5/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 6/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 7/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 8/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 9/25
1263/1263 - 95s - 76ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 10/25
1263/1263 - 95s - 75ms/step - accuracy: 0.0080 - loss: nan - val_accuracy: 0.0080 - val_loss: nan
Epoch 11/25
1263/1263 - 95s -

W0000 00:00:1713180806.952930     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


632/632 - 4s - 6ms/step - accuracy: 0.0080 - loss: nan


W0000 00:00:1713180810.245735     199 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update



Fold 5 - Test Accuracy: 0.80%
Trained model saved successfully at: /kaggle/working/DFNet_OpenWorld_WALKIETALKIE.keras


In [15]:
 #Save the model to the Kaggle output directory
model_save_path = '/kaggle/working/DFNet_OpenWorld_WTFPAD.keras'
model.save(model_save_path)
print("Trained model saved successfully at:", model_save_path)


Trained model saved successfully at: /kaggle/working/DFNet_OpenWorld_WTFPAD.keras


In [19]:
import os

# Define the directory for saving the model
expected_directory = '/kaggle/working/'
expected_filename = 'DFNet_OpenWorld_WTFPAD.keras'

# Construct the full path
saved_path_keras = os.path.join(expected_directory, expected_filename)

# Check if the directory exists
if not os.path.exists(expected_directory):
    print("Error: Directory does not exist:", expected_directory)
else:
    # Check if the model was saved successfully
    try:
        # Your code for saving the model goes here
        # For example:
        # model.save(saved_path_keras)
        # If an error occurs during the saving process, it will be caught here
        print("Model saved successfully.")
    except Exception as e:
        print("Error occurred while saving the model:", e)


Model saved successfully.


In [21]:
# Load data for non-defended dataset for OW evaluation
import pickle
import numpy as np
def  LoadDataWalkieTalkie_Evaluation():

    print("Loading defended dataset for open-world scenario for evaluation")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/defended-open-world-walkietalkie-dataset/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)
    try:
        # Load testing data
        with open(dataset_dir + 'X_test_Mon_WalkieTalkie.pkl', 'rb') as handle:
            X_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Mon_WalkieTalkie.pkl', 'rb') as handle:
            y_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'X_test_Unmon_WalkieTalkie.pkl', 'rb') as handle:
            X_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Unmon_WalkieTalkie.pkl', 'rb') as handle:
            y_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))

        X_test_Mon = np.array(X_test_Mon)
        y_test_Mon = np.array(y_test_Mon)
        X_test_Unmon = np.array(X_test_Unmon)
        y_test_Unmon = np.array(y_test_Unmon)

        return X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon

    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load evaluation data
LoadDataWalkieTalkie_Evaluation()

Loading defended dataset for open-world scenario for evaluation


(array([[ 1, -1,  1, ..., -1, -1, -1],
        [ 1,  1, -1, ..., -1, -1, -1],
        [ 1,  1, -1, ..., -1, -1, -1],
        ...,
        [ 1,  1, -1, ...,  0,  0,  0],
        [ 1,  1, -1, ..., -1,  1, -1],
        [ 1, -1,  1, ..., -1, -1, -1]]),
 array([ 0,  0,  0, ..., 99, 99, 99]),
 array([[ 1, -1,  1, ..., -1, -1, -1],
        [ 1, -1,  1, ...,  0,  0,  0],
        [ 1,  1,  1, ..., -1, -1, -1],
        ...,
        [ 1, -1,  1, ..., -1, -1, -1],
        [ 1,  1, -1, ...,  0,  0,  0],
        [ 1, -1,  1, ..., -1, -1, -1]]),
 array([100, 100, 100, ..., 100, 100, 100]))

In [22]:
from keras.models import load_model
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

def Prediction(trained_model = None, dataset = None):
    X_test_Mon = dataset['X_test_Mon'].astype('float32')
    X_test_Unmon = dataset['X_test_Unmon'].astype('float32')
    print ("Total testing data ", len(X_test_Mon) + len(X_test_Unmon))
    X_test_Mon = X_test_Mon[:, :, np.newaxis]
    X_test_Unmon = X_test_Unmon[:, :, np.newaxis]
    result_Mon = trained_model.predict(X_test_Mon, verbose=2)
    result_Unmon = trained_model.predict(X_test_Unmon, verbose=2)
    return result_Mon, result_Unmon
def Evaluation(threshold_val = None, monitored_label = None,
                   unmonitored_label = None, result_Mon = None,
                   result_Unmon = None, log_file = None):
    print ("Testing with threshold = ", threshold_val)
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    # ==============================================================
    # Test with Monitored testing instances
    # evaluation
    for i in range(len(result_Mon)):
        sm_vector = result_Mon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Monitored
                TP = TP + 1
            else: # predicted as Unmonitored and actual site is Monitored
                FN = FN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Monitored
            FN = FN + 1

    # ==============================================================
    # Test with Unmonitored testing instances
    # evaluation
    for i in range(len(result_Unmon)):
        sm_vector = result_Unmon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Unmonitored
                FP = FP + 1
            else: # predicted as Unmonitored and actual site is Unmonitored
                TN = TN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Unmonitored
            TN = TN + 1
            
    print ("TP : ", TP)
    print ("FP : ", FP)
    print ("TN : ", TN)
    print ("FN : ", FN)
    print ("Total  : ", TP + FP + TN + FN)
    TPR = float(TP) / (TP + FN)
    print ("TPR : ", TPR)
    FPR = float(FP) / (FP + TN)
    print ("FPR : ",  FPR)
    Precision = float(TP) / (TP + FP)
    print ("Precision : ", Precision)
    Recall = float(TP) / (TP + FN)
    print ("Recall : ", Recall)
    print ("\n")
    log_file.writelines("%.6f,%d,%d,%d,%d,%.6f,%.6f,%.6f,%.6f\n"%(threshold_val, TP, FP, TN, FN, TPR, FPR, Precision, Recall))

# The evaluation of Open World scenario
def OW_Evaluation():
    evaluation_type = 'OpenWorld_WalkieTalkie'
    print("Evaluation type: ", evaluation_type)

    # Create the 'results' directory if it doesn't exist
    results_dir = '../results/'
    os.makedirs(results_dir, exist_ok=True)

    threshold = 1.0 - 1 / np.logspace(0.05, 2, num=15, endpoint=True)
    file_name = f'{results_dir}{evaluation_type}.csv'
    log_file = open(file_name, "w")  # Open the file in text mode, not binary mode
    # Load data
    dataset = {}
    model_name = ''
    print ("Loading data ...")
    #from utility import LoadDataNoDefOW_Evaluation
    X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon = LoadDataWalkieTalkie_Evaluation()
    # Load pre-trained model saved from 'Open_World_DF_***_Training.py'
    #model_name = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
    model_name = '/kaggle/working/DFNet_OpenWorld_WALKIETALKIE.keras'


    dataset['X_test_Mon'] = X_test_Mon
    dataset['y_test_Mon'] = y_test_Mon
    dataset['X_test_Unmon'] = X_test_Unmon
    dataset['y_test_Unmon'] = y_test_Unmon

    print ("Data loaded!")
    print ("Loading DF model ...")
    print ("The log file will be saved at ", file_name)
    print ("-- The log file will contains")
    print ("-- TP, FP, TN, FN, TPR, FPR, Precision, and Recall for each different threshold")
    print ("-- These results will be used to plot the ROC or Precision&Recall Graph")
    trained_model = load_model(model_name)
    print ("Model loaded!")
    print ("Evaluation Type: ", evaluation_type)
    print ("Use the model from ", model_name)
    result_Mon, result_Unmon = Prediction(trained_model = trained_model, dataset = dataset)
    monitored_label = list(y_test_Mon)
    unmonitored_label = list(y_test_Unmon)
    log_file.writelines("%s,%s,%s,%s,%s,%s  ,%s  ,  %s, %s\n" % ('Threshold', 'TP', 'FP', 'TN', 'FN', 'TPR', 'FPR', 'Precision', 'Recall'))
    for th in threshold:
        Evaluation(threshold_val = th, monitored_label = monitored_label,
                   unmonitored_label = unmonitored_label, result_Mon = result_Mon,
                   result_Unmon = result_Unmon, log_file = log_file)
    log_file.close()  

OW_Evaluation()

Evaluation type:  OpenWorld_WalkieTalkie
Loading data ...
Loading defended dataset for open-world scenario for evaluation
Data loaded!
Loading DF model ...
The log file will be saved at  ../results/OpenWorld_WalkieTalkie.csv
-- The log file will contains
-- TP, FP, TN, FN, TPR, FPR, Precision, and Recall for each different threshold
-- These results will be used to plot the ROC or Precision&Recall Graph
Model loaded!
Evaluation Type:  OpenWorld_WalkieTalkie
Use the model from  /kaggle/working/DFNet_OpenWorld_WALKIETALKIE.keras
Total testing data  29000


W0000 00:00:1713183726.597534     202 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


282/282 - 3s - 9ms/step


W0000 00:00:1713183728.376683     201 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


625/625 - 2s - 3ms/step
Testing with threshold =  0.10874906186625455
TP :  0
FP :  0
TN :  20000
FN :  9000
Total  :  29000
TPR :  0.0
FPR :  0.0


ZeroDivisionError: float division by zero